### Keras RNN으로 BBC 기사 분류

1. 패키지 수입 및 파라미터 설정

In [ ]:
# 패키지 수입
import csv
import numpy as np
import nltk

from keras.preprocessing.text import Tokenizer 
from keras.preprocessing.sequence import pad_sequences # 기사 길이를 맞출 때 사용 
from time import time
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM, Dropout, Embedding
from keras.layers import Bidirectional
from sklearn.metrics import confusion_matrix, f1_score

In [ ]:
# 하이퍼 파라미터 설정
MY_VOCAB = 5000     # 사용할 단어 수, 제일 많이 사용된 단어
MY_EMBED = 64       # 임베딩 차원
MY_HIDDEN = 100     # 뉴런의 개수, LSTM 셀의 규모
MY_LEN = 200        # 기사의 길이 

MY_SPLIT = 0.8      # 학습용 데이터
MY_SAMPLE = 123     # 샘플 기사
MY_EPOCH = 10      # 반복 학습 수. 실험 시간을 줄이기 위해선 낮춰줌. but 정확도 감소
TRAIN_MODE = 1      # 학습 모드와 평가 모드 선택, 학습된 데이터를 파일로 저장할 때 사용

2. 데이터 처리

In [ ]:
# 제외어(stopword) 설정 
nltk.download('stopwords')
MY_STOP = set(nltk.corpus.stopwords.words('english')) # 영어와 관련된 제외어를 불러옴

print('영어 제외어')
print(MY_STOP)
print('제외어 개수 :', len(MY_STOP))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
영어 제외어
{"she's", 'for', 'ourselves', 'who', 've', 'a', 'which', 'in', 'we', 'does', 'and', "should've", "wasn't", 'i', 'herself', 'such', 'other', "you'd", 'll', 'about', 'on', 'because', 'while', 'can', 'under', 'these', 'y', 'you', 'she', 'own', 'd', "needn't", 'below', 'yourself', 'again', 'himself', 'now', 'between', "haven't", 'through', 'him', 'won', 'same', 'yourselves', 'have', 'ma', 'but', 'its', 'they', 'over', 'once', "didn't", 'how', 'he', 'whom', 'do', 'ours', 'her', 'doing', 'up', 'until', 'not', 'been', 'shouldn', "isn't", "it's", "you're", 'as', 'don', "mightn't", 'themselves', 'above', 'didn', 'me', 'our', 'hers', 'ain', 'are', 'had', 'did', 'his', 'hasn', "weren't", 'being', 'both', 'than', 'm', 're', 'couldn', 'only', 'with', 'mightn', 'of', 'before', 'o', 'their', 'theirs', 'hadn', 'itself', "wouldn't", 'an', 'myself', 'mustn', 'having', 'each', 'at', 'this

In [ ]:
# 데이터 보관 창고
original = [] # 원본 기사
articles = [] # 제외어를 삭제한 기사
labels = [] # 카테고리

In [ ]:
# BBC 파일 읽고 처리
with open('/content/drive/MyDrive/Colab Notebooks/data/bbc-text.csv','r') as file:
    # 컬럼 이름 읽기
    reader = csv.reader(file)    
    next(reader) # 컬럼 명 다음의 데이터부터

    # 기사 하나(한 행)씩 처리
    for row in reader:
        # 카테고리 저장
        labels.append(row[0])
        
        # 원본 기사 저장
        original.append(row[1])

        # 제외어 삭제 하기
        news = row[1]
        for word in MY_STOP:
            mask = ' ' + word + ' ' 
            news = news.replace(mask, ' ') # news에 mask를 ' '로 replace한 내용 저장
        articles.append(news)

print('처리한 기사 수 :', len(articles))

처리한 기사 수 : 2225


In [ ]:
# 샘플 기사 출력
print('샘플 기사 원본')
print(original[MY_SAMPLE]) # MY_SAMPLE번 째 기사 확인
print(labels[MY_SAMPLE])
# 알파벳 수 : len(original[MY_SAMPLE])
print('총 단어 수 :', len(original[MY_SAMPLE].split())) # 디폴트는 공백

샘플 기사 원본
screensaver tackles spam websites net users are getting the chance to fight back against spam websites  internet portal lycos has made a screensaver that endlessly requests data from sites that sell the goods and services mentioned in spam e-mail. lycos hopes it will make the monthly bandwidth bills of spammers soar by keeping their servers running flat out. the net firm estimates that if enough people sign up and download the tool  spammers could end up paying to send out terabytes of data.   we ve never really solved the big problem of spam which is that its so damn cheap and easy to do   said malte pollmann  spokesman for lycos europe.  in the past we have built up the spam filtering systems for our users   he said   but now we are going to go one step further.    we ve found a way to make it much higher cost for spammers by putting a load on their servers.  by getting thousands of people to download and use the screensaver  lycos hopes to get spamming websites constantly r

In [ ]:
# 제외어 처리 결과
print('샘플 기사 제외어 삭제본')
print(articles[MY_SAMPLE])
print('총 단어 수 :', len(articles[MY_SAMPLE].split())) # 디폴트는 공백

샘플 기사 제외어 삭제본
screensaver tackles spam websites net users getting chance fight back spam websites  internet portal lycos made screensaver endlessly requests data sites sell goods services mentioned spam e-mail. lycos hopes make monthly bandwidth bills spammers soar keeping servers running flat out. net firm estimates enough people sign download tool  spammers could end paying send terabytes data.   never really solved big problem spam damn cheap easy   said malte pollmann  spokesman lycos europe.  past built spam filtering systems users   said   going go one step further.    found way make much higher cost spammers putting load servers.  getting thousands people download use screensaver  lycos hopes get spamming websites constantly running almost full capacity. mr pollmann said intention stop spam websites working subjecting much data cope with. said screensaver carefully written ensure amount traffic generated user overload web.  every single user contribute three four megabytes per d

In [ ]:
# Tokenizer 처리
A_token = Tokenizer(num_words=MY_VOCAB, # 데이터(단어)를 몇 개 쓸 것인가
                    oov_token='OOV') # 'Out Of Vocab'. 
                                     # 자주 쓰이는 5000개 단어보다 덜 쓰이는(어려운) 단어 처리를 어떻게 할 것 인가
                                     # 그 단어를 OOV로 설정하겠다

A_token.fit_on_texts(articles) # articles의 단어를 숫자로 바꾸기 위한 준비과정(hash function을 만듦)
A_tokenized = A_token.texts_to_sequences(articles) # 토큰 결과. 실제로 영어 단어를 숫자로 바꾸어 줌
# hash function

# 전환의 예
# 숫자 -> 단어
print(A_token.sequences_to_texts([[1]])) # 1이라는 숫자를 단어로 역전환 => OOV(누락된 단어)가 출력됨.
# 단어 -> 숫자
print(A_token.texts_to_sequences(['the'])) # 'the' 단어가 어떤 숫자로 변환? 인기도와 관계 x

['OOV']
[[1113]]


In [ ]:
# Token 처리 결과 출력
sample = A_tokenized[MY_SAMPLE]
print(sample) 

[3171, 1, 816, 878, 115, 136, 382, 347, 716, 28, 816, 878, 228, 1, 3172, 27, 3171, 1, 4869, 204, 569, 733, 1771, 126, 4025, 816, 260, 395, 3172, 700, 21, 1649, 3629, 2848, 2606, 1, 2324, 2550, 453, 2918, 570, 115, 63, 2290, 381, 7, 1161, 780, 1859, 2606, 11, 92, 1571, 1051, 1, 204, 281, 154, 1, 138, 364, 816, 1, 2225, 847, 2, 1, 1, 178, 3172, 139, 255, 1109, 816, 1, 726, 136, 2, 52, 60, 10, 818, 3790, 195, 41, 21, 56, 495, 245, 2606, 1362, 1, 2550, 382, 1021, 7, 780, 70, 3171, 3172, 700, 23, 1, 878, 3993, 453, 343, 322, 1393, 3, 1, 2, 3427, 582, 816, 878, 297, 1, 56, 204, 2295, 2403, 2, 3171, 2708, 1069, 660, 812, 1287, 3884, 1539, 1, 466, 224, 504, 1539, 1, 31, 96, 1, 681, 111, 2, 10, 1898, 912, 2, 381, 7, 1161, 1, 878, 11, 722, 256, 1, 1287, 224, 504, 111, 3172, 79, 70, 260, 395, 716, 28, 2, 3, 1, 4, 1604, 10, 823, 455, 158, 823, 455, 2, 569, 2179, 4025, 816, 260, 395, 891, 733, 1771, 126, 221, 3677, 569, 316, 86, 1051, 816, 260, 395, 3677, 23, 1, 1452, 681, 111, 415, 569, 3171, 760,

In [ ]:
# 기사 통계 내기
# 제외어 제외, 토큰 처리 후.
longest = max([len(x) for x in A_tokenized])
print('제일 긴 기사 :', longest)

shortest = min([len(x) for x in A_tokenized])
print('제일 짧은 기사 :', shortest)

print('총 단어 수 :', len(A_token.word_counts)) # A_token.word_counts : 단어가 사용된 횟수 출력
# 총 단어 수 n개 중 MY_VOCAB개만 기계학습에 사용

제일 긴 기사 : 2280
제일 짧은 기사 : 50
총 단어 수 : 29698


In [ ]:
# 기사 길이 맞추기 -> 모든 기사의 길이를 맞춰줌
A_tokenized = pad_sequences(A_tokenized,
                            maxlen=MY_LEN,
                            padding='post', # 200 단어보다 짧은 기사는 0으로 뒷부분 패딩 처리
                            truncating='post') # 200 단어보다 긴 기사는 뒷 부분 삭제 

# 기사 길이 확인
longest = max([len(x) for x in A_tokenized])
print('제일 긴 기사 :', longest)

shortest = min([len(x) for x in A_tokenized])
print('제일 짧은 기사 :', shortest)

제일 긴 기사 : 200
제일 짧은 기사 : 200


In [ ]:
# 라벨 tokenization
C_token = Tokenizer()
C_token.fit_on_texts(labels) # 변환 준비 과정. hash function을 만듦
C_tokenized = C_token.texts_to_sequences(labels) # 카테고리를 숫자로 변환한 결과

# 전환의 예
print(C_token.word_index)
print(C_tokenized)

{'sport': 1, 'business': 2, 'politics': 3, 'tech': 4, 'entertainment': 5}
[[4], [2], [1], [1], [5], [3], [3], [1], [1], [5], [5], [2], [2], [3], [1], [2], [3], [1], [2], [4], [4], [4], [1], [1], [4], [1], [5], [4], [3], [5], [3], [4], [5], [5], [2], [3], [4], [5], [3], [2], [3], [1], [2], [1], [4], [5], [3], [3], [3], [2], [1], [3], [2], [2], [1], [3], [2], [1], [1], [2], [2], [1], [2], [1], [2], [4], [2], [5], [4], [2], [3], [2], [3], [1], [2], [4], [2], [1], [1], [2], [2], [1], [3], [2], [5], [3], [3], [2], [5], [2], [1], [1], [3], [1], [3], [1], [2], [1], [2], [5], [5], [1], [2], [3], [3], [4], [1], [5], [1], [4], [2], [5], [1], [5], [1], [5], [5], [3], [1], [1], [5], [3], [2], [4], [2], [2], [4], [1], [3], [1], [4], [5], [1], [2], [2], [4], [5], [4], [1], [2], [2], [2], [4], [1], [4], [2], [1], [5], [1], [4], [1], [4], [3], [2], [4], [5], [1], [2], [3], [2], [5], [3], [3], [5], [3], [2], [5], [3], [3], [5], [3], [1], [2], [3], [3], [2], [5], [1], [2], [2], [1], [4], [1], [4], [4], 

In [ ]:
# 데이터 4분할
C_tokenized = np.array(C_tokenized) # list를 numpy로 변환
X_train, X_test, Y_train, Y_test = train_test_split(A_tokenized, #  입력 data
                                                    C_tokenized, # 출력 data
                                                    train_size=MY_SPLIT,
                                                    shuffle=False)

# 데이터 모양 확인 
print('학습용 입력 데이터 모양 :', X_train.shape)
print('학습용 출력 데이터 모양 :', Y_train.shape)

print('평가용 입력 데이터 모양 :', X_test.shape)
print('평가용 출력 데이터 모양 :', Y_test.shape)

학습용 입력 데이터 모양 : (1780, 200)
학습용 출력 데이터 모양 : (1780, 1)
평가용 입력 데이터 모양 : (445, 200)
평가용 출력 데이터 모양 : (445, 1)


3. 인공 신경망 구현

In [ ]:
# RNN 구현
model = Sequential()

model.add(Embedding(input_dim=MY_VOCAB, # MY_VOCAB개를
                    output_dim=MY_EMBED)) # MY_EMBED개로

model.add(Dropout(rate=0.5)) # Dropout : 임의의 뉴런의 출력을 일부로 0으로 만드는 작업
                             # 과적합(overfitting) 방지하기 위해 뉴런 몇 개를 죽임
                             # 과적합은 새로운 문제해결에 해가 될 수 있음

model.add(Bidirectional(LSTM(units=MY_HIDDEN)))

model.add(Dense(units=6,
                activation='softmax'))

print('RNN 요약')
model.summary()

RNN 요약
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          320000    
_________________________________________________________________
dropout (Dropout)            (None, None, 64)          0         
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               132000    
_________________________________________________________________
dense (Dense)                (None, 6)                 1206      
Total params: 453,206
Trainable params: 453,206
Non-trainable params: 0
_________________________________________________________________


4. 인공 신경망 학습

In [ ]:
# RNN 학습
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['acc'])

print(' 학습 시작')
begin = time()

model.fit(x=X_train,
          y=Y_train,
          epochs=MY_EPOCH,
          verbose=1)

end = time()
print('학습 시간 : {:.2f}'.format(end - begin))

 학습 시작
Epoch 1/10
56/56 [==============================] - 11s 25ms/step - loss: 1.6751 - acc: 0.2364
Epoch 2/10
56/56 [==============================] - 1s 23ms/step - loss: 1.2493 - acc: 0.5235
Epoch 3/10
56/56 [==============================] - 1s 22ms/step - loss: 0.6446 - acc: 0.8225
Epoch 4/10
56/56 [==============================] - 1s 22ms/step - loss: 0.5070 - acc: 0.8320
Epoch 5/10
56/56 [==============================] - 1s 22ms/step - loss: 0.1724 - acc: 0.9622
Epoch 6/10
56/56 [==============================] - 1s 22ms/step - loss: 0.1671 - acc: 0.9618
Epoch 7/10
56/56 [==============================] - 1s 22ms/step - loss: 0.0578 - acc: 0.9925
Epoch 8/10
56/56 [==============================] - 1s 22ms/step - loss: 0.0304 - acc: 0.9953
Epoch 9/10
56/56 [==============================] - 1s 22ms/step - loss: 0.0444 - acc: 0.9910
Epoch 10/10
56/56 [==============================] - 1s 23ms/step - loss: 0.0134 - acc: 0.9997
학습 시간 : 22.11


5. 인공 신경망 평가

In [ ]:
# RNN 평가
score = model.evaluate(X_test,
                       Y_test,
                       verbose=0)

print('최종 손실값 : {:.2f}'.format(score[0]))
print('최종 정확도 : {:.2f}'.format(score[1]))

최종 손실값 : 0.22
최종 정확도 : 0.94


6. 인공 신경망 예측

In [ ]:
# RNN 예측
pred = model.predict(X_test) # 0번째 output은 대부분 사용하지 않음
pred = pred.argmax(axis=1) # 제일 큰 값이 몇 번째 있나. 몇 번 축을 쓸 지 정해줘야함. 열 사용
print(pred)
print(Y_test.flatten()) # Y_test는 2차원 데이터로 한 줄로 출력됨

[5 4 3 1 1 4 3 4 5 5 3 3 2 5 1 5 5 2 1 3 4 2 1 5 4 3 3 1 1 3 2 2 2 2 5 2 3
 3 4 4 5 3 5 2 3 1 1 5 4 2 4 1 2 2 3 1 1 3 3 5 5 3 2 3 3 2 4 3 3 3 3 3 5 5
 4 3 1 4 1 4 5 1 1 5 4 5 4 1 4 1 1 5 5 2 5 5 3 2 1 4 4 3 2 1 2 4 1 3 5 1 1
 2 3 4 4 2 2 1 3 5 1 1 3 5 4 1 5 2 3 1 3 4 5 1 3 2 5 3 5 3 1 3 3 2 3 2 4 1
 2 5 2 1 1 4 4 3 4 3 3 1 1 1 2 4 5 3 1 2 1 2 4 2 2 2 2 1 1 1 2 2 5 2 2 2 1
 1 1 4 4 1 1 1 2 5 4 4 4 3 2 2 4 2 4 1 1 3 3 3 1 1 3 3 4 2 1 1 1 1 2 1 2 2
 3 2 1 3 1 4 4 1 4 2 5 2 1 2 4 4 3 5 2 5 2 4 3 5 3 5 5 4 3 4 4 2 3 1 5 2 3
 5 2 4 1 4 3 1 3 2 3 3 2 2 2 4 3 2 3 2 5 3 1 3 3 1 5 4 4 2 4 1 4 3 2 1 4 4
 4 1 5 1 3 2 3 3 5 4 2 4 1 5 5 1 2 5 4 4 1 5 2 3 3 3 4 4 2 3 2 4 3 5 5 4 2
 4 5 4 4 1 3 1 1 3 5 5 2 3 3 1 2 2 4 2 4 4 1 2 3 1 2 2 1 4 1 4 5 1 1 5 2 4
 1 1 3 4 3 3 1 1 3 2 4 4 4 2 1 5 5 4 2 3 4 1 1 4 4 3 2 1 5 4 1 3 4 1 2 2 2
 1 1 4 1 3 4 2 2 1 2 3 2 2 5 3 4 3 4 5 3 4 5 1 3 5 4 4 2 4 5 4 1 4 2 3 5 3
 1]
[5 4 3 1 1 4 2 4 5 5 3 3 2 5 1 5 5 2 1 3 4 2 1 5 4 3 3 1 1 2 2 2 2 2 5 2 3
 3 4 4 5 3 5 2 3 1 1 

In [ ]:
# 혼동 행렬 출력
print('혼동 행렬')
print(confusion_matrix(y_true=Y_test,
                       y_pred=pred)) # 대각선에 있는 값은 맞은 것.
                                     # 혼동 행렬에서 행 : 예측, 열 : 정답
                                     # ex) [0][0] : 1번을 예측해서 맞은 것 (사실상 [1][1])
                                     # ex) [2][0] : 1번 답을 3번으로 예측한 것

혼동 행렬
[[99  0  0  0  2]
 [ 0 91 10  4  1]
 [ 0  1 83  2  0]
 [ 1  0  0 84  1]
 [ 0  1  1  3 61]]


In [ ]:
# 실제 기사로 분류
news = ["'Paul Pogba's second-half volley was enough to give Manchester United victory at Burnley and send them three points clear at the top of the Premier League. United dominated a contest in which Burnley failed to register a single shot on target until stoppage time. But they were struggling to make a breakthrough until Marcus Rashford picked Pogba out with an excellent cross to the edge of the area. The Frenchman's connection was perfect, although it took a deflection off Matthew Lowton to ensure the ball went past Nick Pope and into the Burnley net. Although Burnley had three decent chances in a frantic ending, United secured the win to head the table after 17 rounds of matches.'"]

news = A_token.texts_to_sequences(news)
print(news)

news = pad_sequences(news, #처리할 데이터
                     maxlen=MY_LEN,
                     padding='post', # 뒷부분 0으로 패딩처리
                     truncating='post')

# print(news)
pred = model.predict(news) # 확률값
pred = pred.argmax(axis=1)
print('RNN 추측값 :', pred)

# {'sport': 1, 'business': 2, 'politics': 3, 'tech': 4, 'entertainment': 5}


[[1, 1, 64, 104, 4061, 3917, 381, 476, 209, 658, 190, 434, 3496, 4402, 2002, 1051, 598, 31, 550, 373, 3496, 1113, 66, 1635, 1113, 2568, 463, 190, 1446, 1385, 1751, 619, 1, 4402, 535, 476, 2991, 1385, 504, 811, 584, 760, 1, 1, 14, 1, 1, 1, 1848, 476, 21, 1385, 2533, 1, 1, 1, 1309, 1, 570, 2403, 1, 2560, 872, 476, 1113, 2177, 1635, 1113, 826, 1113, 1, 1581, 3917, 2598, 238, 197, 169, 1385, 1, 813, 2820, 1, 476, 660, 1113, 692, 293, 255, 2852, 1, 2002, 1, 1113, 4402, 115, 238, 4402, 3842, 31, 3291, 1368, 619, 1385, 1, 3342, 190, 2626, 1113, 58, 476, 392, 1113, 2366, 1, 579, 1, 1635, 1251, 1]]
RNN 추측값 : [1]
